### ISSUE TITLE
ios 12.3.1 open email fails on first use

### ISSUE THREAD

**Issue by chriscarreck** [katzer/cordova-plugin-email-composer#334] opened 2019-08-07 13:56 UTC
ipad pro
ios 12.3.1 (but also happens on other ios 12 versions)
Cordova 8.1.1
tried email-composer 0.8.15 and 0.9.2

making a call to cordova.plugins.email.open();

When the app is first installed and method called, the email briefly flicks open over the app, but instantly disappears again.
If i click the button to call the same method a second time immediately after the email disappears, it shows again ready for editing as expected.

I have noticed if i pass values to the open() method. The same thing happens, and when the email briefly appears, only the subject is populated. Body and to/from fields are empty.

I can replicate this by resetting and erasing the device, re-installing the app and it occurs every-time on first use when calling open(). 

When i debug the native code of the plugin, on first use of app opening an email for edit, i get the following trace:
2019-08-08 23:06:02.673501+1000 SOS[421:13879] Attempt to present <MFMailComposeViewController: 0x1018e1200> on <MainViewController: 0x10160e590> which is waiting for a delayed presention of <MFMailComposeViewController: 0x10203a600> to complete
2019-08-08 23:06:02.692081+1000 SOS[421:13879] [General] **#CompositionServices _serviceViewControllerReady: NSError Domain=NSCocoaErrorDomain Code=4097**

subsequent attempts do not get the NSError

**Comment by jfoclpf** [comment] 2021-11-29 09:48
most likely duplicate of #363

**Closed by jfoclpf** 2021-11-29 09:48 UTC
