### ISSUE TITLE
Open() is not working for windows 10 cordova app

### ISSUE THREAD

**Issue by gharini11** [katzer/cordova-plugin-email-composer#294] opened 2018-03-08 17:04 UTC
Hi,
I have a universal cordova app for iOS and Windows 10 UWP. 
I have the following code when email button is clicked -

            $cordovaEmailComposer.isAvailable().then(function () {
                var email = {
                    to: '',
                    cc: '',
                    bcc: [],
                    attachments: emailImageArray,
                    subject: subject,
                    body: emailBody,
                    isHtml: true
                };

                $cordovaEmailComposer.open(email).then(null, function () {
                    console.log("Email ready cancel", emailBody);
                });
            }, function () {
                console.log("Email not ready");
            });
        }

It works fine for iOS but for Windows it does not open the draft or throw any error.
plugin version for Windows app - 0.8.7 
cordova-windows - 4.3.0
cordova - 6.0.0

Please let me know how to fix this one.

Thanks!

**Comment by gharini11** [comment] 2018-03-13 20:53
@katzer does it work for Windows 10 apps?

**Comment by QuickCRM** [comment] 2018-10-17 15:21
Hi,
On UWP Windows 10 apps, the mail opens, but attachment(s) are not included.
Our attachments are in ms-appdata:///temp/temp.

**Comment by jfoclpf** [comment] 2021-11-21 22:09
@QuickCRM did you eventually solve this problem?

**Comment by jfoclpf** [comment] 2021-11-29 09:50
duplicate of #252

**Closed by jfoclpf** 2021-11-29 09:50 UTC
