### ISSUE TITLE
able to Open only mail in ios

### ISSUE THREAD

**Issue by 12345097664644674** [katzer/cordova-plugin-email-composer#379] opened 2022-08-29 11:41 UTC
Hello team ,
i am trying to use email-composer in my application and i get to know that in android we are getting the option of all available mail clients like gmail and outlook whatever downloaded in device but in ios email composer is only working with mail not with outlook and gmail i am not getting the popup which shows that which mail client you want outlook ,gmail ,etc i have downloaded outlook and gmail in my ios device but i am not getting the popup to select any one instead of this everytime mail gets opened only

**Comment by jfoclpf** [comment] 2022-08-29 11:51
What is the iOS version?

**Comment by 12345097664644674** [comment] 2022-08-29 11:53
IOS Version -15.5

Thanks & Regards,
Prajwal Sharma


________________________________

**Comment by jfoclpf** [comment] 2022-08-29 12:54
Duplicate of #363

**Closed** 2022-08-29 12:54 UTC
