### ISSUE TITLE
plugin 0.8.2 not found

### ISSUE THREAD

**Issue by eliprodigy** [katzer/cordova-plugin-email-composer#83] opened 2015-01-15 09:01 UTC
Error: version not found: 0.8.2 : de.appplant.cordova.plugin.email-composer/0.8.
2
    at RegClient.<anonymous> (C:\Users\Eli\AppData\Roaming\npm\node_modules\cord
ova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\l
ib\request.js:272:14)
    at Request.self.callback (C:\Users\Eli\AppData\Roaming\npm\node_modules\cord
ova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148:
22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\Eli\AppData\Roaming\npm\node_modules\cordov
a\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:14
)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\Eli\AppData\Roaming\npm\node_module
s\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.j
s:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by dezudas** [comment] 2015-02-09 15:58
I am having the same issue

**Comment by eliprodigy** [comment] 2015-02-09 16:00
i solved this with the older version working just fine 
try it

**Comment by dezudas** [comment] 2015-02-09 16:11
Yes It says 0.8.1 "EmailComposer" but I am not able to work with the plugin, working with it. If you can share something plz.

**Comment by eliprodigy** [comment] 2015-02-09 16:13
ChangeLog

Version 0.8.2 (not yet released)

Added new namespace cordova.plugins.email
Note: The former plugin.email namespace is now deprecated and will be removed with the next major release.
[change:] Unified absolute: and relative: to file:
[change:] Renamed isServiceAvailable to isAvailable
[feature:] app: allows to specify target mail app on Android
[feature:] res: prefix for native ressource attachments
[enhancement:] Support attachments on Windows Phone 8.1
[enhancement:] open supports callbacks
[enhancement:] isHTML can be used next isHtml
[bugfix:] Defaults were ignored


you see not release yet (:

**Comment by fh** [comment] 2015-02-11 09:11
See https://github.com/katzer/cordova-plugin-email-composer/releases for available releases. Also, this issue is a duplicate of #78.

**Closed** 2015-02-27 13:08 UTC
