### ISSUE TITLE
Email Composer not working for IOS 13+

### ISSUE THREAD

**Issue by ocean999882** [katzer/cordova-plugin-email-composer#366] opened 2021-10-18 09:42 UTC
Hello,

The add-on works perfectly with Android, but not with iOS. I've tried with two iphones, both have not installed gmail, only the pre-installed mail application. Is it mandatory to install another application? Or should the default mail application open?

Thank you.

**Comment by PetePrattis** [comment] 2021-10-21 07:38
Check in the info.plist if you have added the url scheme of mailer apps under LSApplicationQueriesSchemes, for example for iMail, gmail & outlook apps:

```
<key>LSApplicationQueriesSchemes</key>
<array>
<string>mailto</string>
<string>googlegmail</string>
<string>ms-outlook</string>
</array>
```

for more info https://github.com/katzer/cordova-plugin-email-composer/issues/363#issuecomment-948338728

**Comment by danielehrhardt** [comment] 2021-11-26 16:31
The Default Mail App does not open on iOS 15. 
Should this work in the Simulator or do i have to use a real Device?

**Comment by jfoclpf** [comment] 2021-11-26 19:08
Yes, you should try in a physical device to be sure it is not a problem
with the plugin. Furthermore some simulators don't even have an email
account configured and thus it might not open.

>

**Comment by jfoclpf** [comment] 2021-11-26 19:13
Furthermore it may help to include this in `config.xml` under `<platform name="ios">`

```xml
    <edit-config target="UIFileSharingEnabled" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
    <edit-config target="LSSupportsOpeningDocumentsInPlace" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
    <edit-config target="UISupportsDocumentBrowser" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
```

**Comment by jfoclpf** [comment] 2021-11-26 19:50
duplicate of #363

**Closed by jfoclpf** 2021-11-26 19:50 UTC
