### ISSUE TITLE
Email Composer fails to open Email if an account is not registered in latest IOS devices(iPhone 11 Pro Max, iPhone X)

### ISSUE THREAD

**Issue by Akshay-Kibbcom** [katzer/cordova-plugin-email-composer#344] opened 2020-01-23 06:08 UTC
When we use Email composer plugin in an IOS device where Email is not registered. The email will not open or pop any error.[IOS 13+]

In older versions, we get a popup saying No Email Account is registered.

```
let email = {
  to: 'max@mustermann.de',
  cc: 'erika@mustermann.de',
  bcc: ['john@doe.com', 'jane@doe.com'],
  attachments: [
    'file://img/logo.png',
    'res://icon.png',
    'base64:icon.png//iVBORw0KGgoAAAANSUhEUg...',
    'file://README.pdf'
  ],
  subject: 'Cordova Icons',
  body: 'How are you? Nice greetings from Leipzig',
  isHtml: true
}

// Send a text message using default options
this.emailComposer.open(email);
```

Any solution to handle this issue??

Reference:
`https://ionicframework.com/docs/native/email-composer`

**Comment by canadaka** [comment] 2020-02-27 17:50
We noticed this same issue.

**Comment by rychter** [comment] 2020-03-30 09:08
+

**Comment by rychter** [comment] 2020-03-30 09:26
https://stackoverflow.com/questions/58588821/issue-calling-isavailable-method-ionic-native-email-composer

**Comment by jfoclpf** [comment] 2021-11-26 20:06
duplicate of #363

**Closed by jfoclpf** 2021-11-26 20:06 UTC
