### ISSUE TITLE
Failed to install 'cordova-plugin-email-composer' - (cant find AndroidManifest.xml)

### ISSUE THREAD

**Issue by svranch** [katzer/cordova-plugin-email-composer#285] opened 2018-01-04 00:46 UTC
I upgraded to Cordova 8.0 - but now get this error:

> Failed to install 'cordova-plugin-email-composer': Error: ENOENT: no such file or directory, open '{project path}\platforms\android\AndroidManifest.xml' at Object.fs.openSync blah blah blah

Per the post at the below URL, katzer needs to change the path in the plugin:

> It is now in app/src/main/AndroidManifest.xml.  If the plugin is writing on it, it should be updated to write on the right place. Read the cordova-android 7.0.0 release blog post at http://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

The above post can be found at https://stackoverflow.com/questions/47926796/cordova-does-not-create-androidmanifest-xml

BUT IN THE MEANTIME, this post on same web page saved my day:

> Cordova CLI v8.0 will use cordova-android@7.0.0 by default.  As most of the cordova plugins do not support cordova-android@7.0.0 yet, you can also try using the older one by specifying version:
`cordova platform add android@6.4.0`

Just be sure to remove the more recent android first ...

`cordova platform rm android`

**Comment by katzer** [comment] 2018-01-06 12:32
@svranch I just installed the plugin with Cordova CLI v8.0 and cordova-android 7.0.0 without any issues.

**Comment by mevinDhun** [comment] 2018-01-22 12:02
Hi,
I upgraded to cordova CLI v8 and getting same error:
```
Failed to install 'cordova-plugin-email-composer': Error: ENOENT: no such file or directory, open '/home/travis/build/SharinPix/sharinpix-app/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/home/travis/build/SharinPix/sharinpix-app/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/home/travis/build/SharinPix/sharinpix-app/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/home/travis/build/SharinPix/sharinpix-app/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/home/travis/build/SharinPix/sharinpix-app/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/travis/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
Failed to restore plugin "cordova-plugin-email-composer" from config.xml. You might need to try adding it again. Error: Error: 
```
Seems to be caused by the change in the path of Android manifest in cordova v7

**Comment by ThorvaldAagaard** [comment] 2018-02-13 10:45
There seems to be a problem with a lot of plugins,when moving to cordova-android 7.0.0, I had to downgrade to cordova-android 6.3.3

**Comment by cepm-nate** [comment] 2018-03-28 00:18
Any update from the author of this plugin?

**Comment by katzer** [comment] 2018-11-09 10:55
So with latests cordova, cordova-android, ... I dont receive an error. I also just updated the plugin.xml

**Closed by katzer** 2018-11-09 10:55 UTC
