### ISSUE TITLE
App crashes if you don't have any Mail accounts signed in (iOS)

### ISSUE THREAD

**Issue by iarry** [katzer/cordova-plugin-email-composer#172] opened 2016-02-24 23:11 UTC
I was using an iPhone 5, iOS 9.0.1 with no Mail accounts added. I'm getting a EXC_BAD_ACCESS
 at this line
```objective-c
// CDVViewController.m
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
...
NSString* res = [webView stringByEvaluatingJavaScriptFromString:jsCall];
...
}
```

Console doesn't seem to provide anything useful, here's the output from Xcode (there's nothing in a web console)

```
2016-02-24 15:57:12.996 App[470:55719] bool _WebTryThreadLock(bool), 0x17dcdcd0: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x33751a67 WebThreadLock
2   0x28a8c499 <redacted>
3   0xab29f -[CDVViewController shouldAutorotateToInterfaceOrientation:]
4   0x4bfa5 -[MainViewController shouldAutorotateToInterfaceOrientation:]
5   0xab383 -[CDVViewController supportedInterfaceOrientations]
6   0x286c2f8f <redacted>
7   0x28914dc7 <redacted>
8   0x286c2f8f <redacted>
9   0x286cc417 <redacted>
10  0x286cc3b3 <redacted>
11  0x286cad1f <redacted>
12  0x28648f3b <redacted>
13  0x28648471 <redacted>
14  0x28648317 <redacted>
15  0x28654de7 <redacted>
16  0x2865479b <redacted>
17  0x28653fa1 <redacted>
18  0x286c29bd <redacted>
19  0x28ed752b <redacted>
20  0x28ed7571 <redacted>
21  0x28ed5f0d <redacted>
22  0x28a8a4bd <redacted>
23  0x264ceb15 <redacted>
24  0x916c3 -[APPEmailComposerImpl mailComposerFromProperties:delegateTo:]
25  0x90f17 -[APPEmailComposer presentMailComposerFromProperties:]
26  0x90d6f __25-[APPEmailComposer open:]_block_invoke
27  0x495dbf _dispatch_call_block_and_release
28  0x4a20cf _dispatch_root_queue_drain
29  0x4a19c1 _dispatch_worker_thread3
30  0x36785e29 _pthread_wqthread
31  0x36785a18 start_wqthread
(lldb) 
```

If I log into any account in Mail it works perfectly fine.

**Comment by lunchbag** [comment] 2016-02-25 02:44
I reported a similar if not same issue earlier: https://github.com/katzer/cordova-plugin-email-composer/issues/160

**Comment by accidbright** [comment] 2016-02-25 12:19
Faces the same issue. Stack trace is almost similar. Was reproduced on iPod Touch 4 with iOS 6.1.2. Looks like this is iOS version independent. Also reproduced only if mail account is not configured.

**Comment by katzer** [comment] 2016-02-25 12:30
@iarry Can you try out if you have same issue with latest dev version? I've tested it with latest iOS, cordova-ios and without account and got no crash. Instead `isAvailable` returns correct information that no account is set up.

**Comment by accidbright** [comment] 2016-02-25 13:28
Works wrong with current **master** branch version. Is available returns true with no account
`if (![_impl canSendMail:scheme]) {
    NSLog(@"Dont know how to handle %@. Using iMail instead.", scheme);
    scheme = @"mailto:";
}`
looks strange because `canSendMail:` always returns an array. But it seems that problem not here.
Another strange place I've found in `canSendMail:`
`canSendMail = canSendMail||withScheme;`
Debugger says to me, that if `canSendMail == false` and `withScheme == true`, then result is `false` too.
Don't know if this really helpful...

**Comment by katzer** [comment] 2016-02-25 15:47
@accidbright Trust me the crash has been fixed in 0.8.3-dev and will be available with v0.8.3. You can run the sample app if you like. 

BTW the code you've posted comes from v0.8.2.

**Comment by accidbright** [comment] 2016-02-26 09:00
Where can I get 0.8.3-dev? Only master and example branches are available to me. Or am I missing something?

**Comment by katzer** [comment] 2016-02-29 15:31
@accidbright 0.8.3-dev means master

**Closed** 2016-03-01 09:50 UTC
